language: generic 
sudo: required

services: 
    - docker

before_install
    - docker build -t imkiransuvarna/docker-react-setup -f Dockerfile.dev .

script:
    - docker run -e CI=true imkiransuvarna/docker-react-setup npm run test -- --coverage