language: generic 
sudo: required

services: 
    - docker

before_install:
    - docker build -t imkiransuvarna/docker-react-setup -f Dockerfile.dev .

script:
    - docker run -e CI=true imkiransuvarna/docker-react-setup npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react-setup"
    env: "DockerReactSetup-env"
    bucket_name: "elasticbeanstalk-ap-south-1-280685327061"
    bucket_path: "docker-react-setup"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY